spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?serverTimezone=UTC
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 215MB

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: false

file:
  upload-dir: pdf
springdoc:
  show-actuator: true
api:
  security:
    token:
      secret: ${SECRET:secret}

