CREATE TABLE files
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    file_name         VARCHAR(255),
    file_download_uri VARCHAR(255),
    file_type         VARCHAR(255),
    upload_date       TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_files PRIMARY KEY (id)
);